# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55e713baa5bb012eb8967f5cca50df7995be96d6b992a91dff45dfd555c8809515a15195381180a0cca23ef0007eaf2f71d0abb887ec6ff17d747e9f6d26d812

test:
  secret_key_base: e486202722fc5dac067fea010011425b4b144af63eaa500f31a9d837c833b15c93a6ed4af116b94141d9ad20ac951e49a6a022c01ea97575d6a911528f28cc4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
